---
name: Build - Ubuntu - ARM

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'src/**'
  push:
    paths:
      - 'src/**'

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  MAKEFLAGS: '-j 4'

jobs:
  job:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [Beats-ARM]
        buildtype: [linux-release, linux-debug]
        include:
          - os: Beats-ARM
            triplet: x64-linux

    steps:
      - name: Cancel Previous Runs
        if: github.ref != 'refs/heads/main'
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          cancel_others: true

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install Linux Dependencies
        run: >
          sudo apt-get update && sudo apt-get install ccache linux-headers-$(uname -r)

      - name: Switch to gcc-12
        run: |
          sudo apt install gcc-12 g++-12 -y
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12
          sudo update-alternatives --set gcc /usr/bin/gcc-12

      - name: CCache
        uses: hendrikmuhs/ccache-action@main
        with:
          max-size: "1G"
          key: ccache-${{ matrix.os }}-${{ matrix.buildtype }}
          restore-keys: |
            ccache-${{ matrix.os }}

      - name: Restore artifacts and install vcpkg
        id: vcpkg-step
        run: |
          vcpkgCommitId=$(grep '.builtin-baseline' vcpkg.json | awk -F: '{print $2}' | tr -d '," ')
          echo "vcpkg commit ID: $vcpkgCommitId"
          echo "VCPKG_GIT_COMMIT_ID=$vcpkgCommitId" >> $GITHUB_ENV

      - name: Get vcpkg commit id from vcpkg.json
        uses: lukka/run-vcpkg@main
        with:
          vcpkgGitURL: "https://github.com/microsoft/vcpkg.git"
          vcpkgGitCommitId: ${{ env.VCPKG_GIT_COMMIT_ID }}

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@main

      - name: Run CMake
        uses: lukka/run-cmake@main
        with:
          configurePreset: ${{ matrix.buildtype }}
          buildPreset: ${{ matrix.buildtype }}
          configurePresetAdditionalArgs: "['-DBUILD_TESTS=ON']"

      - name: Create and Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: canary-${{ matrix.os }}-${{ matrix.buildtype }}-${{ github.sha }}
          path: |
            ${{ github.workspace }}/build/${{ matrix.buildtype }}/bin/

      - name: Run Unit Tests
        run: |
          cd ${{ github.workspace }}/build/${{ matrix.buildtype }}/tests/unit
          ctest --verbose

#      - name: Run Integration Tests
#        run: |
#          cd ${{ github.workspace }}/build/${{ matrix.buildtype }}/tests/integration
#          ctest --verbose
